substitutions:
# Based on the following time & date formats:
  time_format12: "%l:%M%p" # 1:25PM
  date_format: "%b %d" # Jan 01
  date_formatA: "%a" # Mon

# for 8-MD-06INKM:
  # Replace characters: Unicode character:Fubata byte (characters that already exist on the device, can use decimal, hex, or binary in MSB-LSB order)
  # Some characters are available (or their Latin similars): ΙαΦβΜρΑπούλγΣΟΝΔΚΤΠμ
  replace: "Ι:73;α:176;Φ:228;β:177;Μ:77;ρ:186;Α:65;π:226;ο:111ύ:163;λ:183;γ:89;Σ:191;Ο:79;Ν:78;Δ:179;Κ:75;Τ:84;Π:185;μ:184;"
  # Custom characters: Unicode character:column1,column2,column3,column4,column5 (binary painting from bottom to top)
  # And some are not: άενικτέυί
  custom: "ά:120,68,36,25,103;ε:28,42,42,34,20;ν:6,24,32,30,2;ι:0,0,60,32,16;κ:0,60,8,52,0;τ:4,4,60,36,20;έ:28,42,42,35,21;υ:28,32,32,32,60;ί:0,0,60,33,17;"

text_sensor:
  - platform: template
    id: time_text
    name: "$friendly_name Replacement Time Text"
    entity_category: diagnostic
    update_interval: never
    internal: true
    filters:
      - append: ""
      - prepend: ""
      - substitute:
        - "AM -> πμ"
        - "PM -> μμ"
  - platform: template
    id: date_text
    name: "$friendly_name Replacement Date Text"
    entity_category: diagnostic
    update_interval: never
    internal: true
    filters:
      - append: ""
      - prepend: ""
      - substitute:
        - "Jan -> Ιαν"
        - "Feb -> Φεβ"
        - "Mar -> Μάρ"
        - "Apr -> Απρ"
        - "May -> Μάι"
        - "Jun -> Ιούν"
        - "Jul -> Ιούλ"
        - "Aug -> Αύγ"
        - "Sep -> Σεπ"
        - "Oct -> Οκτ"
        - "Nov -> Νοέ"
        - "Dec -> Δεκ"
  - platform: template
    id: dateA_text
    name: "$friendly_name Replacement Date A Text"
    entity_category: diagnostic
    update_interval: never
    internal: true
    filters:
      - append: ""
      - prepend: ""
      - substitute:
        - "Sun -> Κυρ"
        - "Mon -> Δευ"
        - "Tue -> Τρί"
        - "Wed -> Τετ"
        - "Thu -> Πέμ"
        - "Fri -> Παρ"
        - "Sat -> Σάβ"